/**
 * sync-release.ts
 * ----------------
 * Fetches the latest release from the Claude Config GitHub repo and writes
 * NEXT_PUBLIC_RELEASE_* env vars to .env.local. Wired into prebuild and
 * invoked by the GitHub Actions workflow on tag push.
 *
 * Idempotent. Falls back silently (writes nothing) if the API is unreachable
 * so local offline builds still succeed using the hardcoded constants in
 * lib/constants.ts.
 */

import { writeFileSync, existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { config as loadDotenv } from "dotenv";

const REPO = "ayan-de/claude-config";
const API = `https://api.github.com/repos/${REPO}/releases/latest`;
const ENV_FILE = resolve(process.cwd(), ".env.local");
const TIMEOUT_MS = 8000;

interface GitHubAsset {
  name: string;
  browser_download_url: string;
  size: number;
  /** e.g. "sha256:2d5cb8…". Exposed by the Releases API since 2024. */
  digest?: string | null;
}

interface GitHubRelease {
  tag_name: string;
  name: string;
  published_at: string;
  html_url: string;
  assets: GitHubAsset[];
}

interface SyncResult {
  tag: string;
  version: string;
  assets: Record<string, { url: string; size: string } | undefined>;
  checksums: Record<string, string>;
}

/** Pick the asset whose filename matches a token. Returns the first match. */
function pickAsset(assets: GitHubAsset[], patterns: RegExp[]): GitHubAsset | undefined {
  for (const pattern of patterns) {
    const found = assets.find((a) => pattern.test(a.name));
    if (found) return found;
  }
  return undefined;
}

function parseSize(bytes: number): string {
  const mb = bytes / (1024 * 1024);
  return `${mb.toFixed(2)} MB`;
}

/** Normalize an asset digest ("sha256:abc…") to a bare hex string. */
function parseDigest(digest: string | null | undefined): string {
  if (!digest) return "";
  return digest.replace(/^sha256:/i, "").trim();
}

async function fetchLatestRelease(): Promise<SyncResult | null> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);

  try {
    const res = await fetch(API, {
      signal: controller.signal,
      headers: {
        Accept: "application/vnd.github+json",
        "User-Agent": "claude-config-marketing-sync",
        ...(process.env.GITHUB_TOKEN
          ? { Authorization: `Bearer ${process.env.GITHUB_TOKEN}` }
          : {}),
      },
    });
    clearTimeout(timer);

    if (!res.ok) {
      console.warn(`[sync-release] GitHub API returned ${res.status}`);
      return null;
    }

    const release = (await res.json()) as GitHubRelease;
    const tag = release.tag_name; // e.g. "v0.1.3"
    const version = tag.replace(/^v/, ""); // "0.1.3"

    const assets = release.assets;

    const deb = pickAsset(assets, [/Claude\.Config_.*\.deb$/]);
    const rpm = pickAsset(assets, [/Claude\.Config-.*\.rpm$/]);
    const appimage = pickAsset(assets, [/Claude\.Config_.*\.AppImage$/]);
    const dmg = pickAsset(assets, [/Claude\.Config_.*\.dmg$/]);
    const msi = pickAsset(assets, [/Claude\.Config_.*\.msi$/]);
    const exe = pickAsset(assets, [/Claude\.Config_.*-setup\.exe$/]);
    const appTar = pickAsset(assets, [/Claude\.Config_.*\.app\.tar\.gz$/]);

    return {
      tag,
      version,
      assets: {
        deb: deb && { url: deb.browser_download_url, size: parseSize(deb.size) },
        rpm: rpm && { url: rpm.browser_download_url, size: parseSize(rpm.size) },
        appimage: appimage && {
          url: appimage.browser_download_url,
          size: parseSize(appimage.size),
        },
        dmg: dmg && { url: dmg.browser_download_url, size: parseSize(dmg.size) },
        msi: msi && { url: msi.browser_download_url, size: parseSize(msi.size) },
        exe: exe && { url: exe.browser_download_url, size: parseSize(exe.size) },
        appTar: appTar && {
          url: appTar.browser_download_url,
          size: parseSize(appTar.size),
        },
      },
      checksums: {
        deb: parseDigest(deb?.digest),
        rpm: parseDigest(rpm?.digest),
        appimage: parseDigest(appimage?.digest),
        dmg: parseDigest(dmg?.digest),
        msi: parseDigest(msi?.digest),
        exe: parseDigest(exe?.digest),
        appTar: parseDigest(appTar?.digest),
      },
    };
  } catch (err) {
    clearTimeout(timer);
    console.warn(`[sync-release] fetch failed: ${(err as Error).message}`);
    return null;
  }
}

function buildEnv(result: SyncResult): string {
  const { tag, version, assets, checksums } = result;
  const get = (k: keyof typeof assets) => assets[k]?.url ?? "";
  const size = (k: keyof typeof assets) => assets[k]?.size ?? "";
  const sha = (k: keyof typeof checksums) => checksums[k] ?? "";

  return [
    "# Generated by scripts/sync-release.ts — do not edit.",
    `# Source: https://github.com/${REPO}/releases/tag/${tag}`,
    `# Synced at: ${new Date().toISOString()}`,
    "",
    `NEXT_PUBLIC_APP_VERSION=${version}`,
    `NEXT_PUBLIC_RELEASE_TAG=${tag}`,
    `NEXT_PUBLIC_RELEASES_URL=https://github.com/${REPO}/releases`,
    `NEXT_PUBLIC_RELEASE_URL=https://github.com/${REPO}/releases/tag/${tag}`,
    "",
    `NEXT_PUBLIC_DOWNLOAD_DEB=${get("deb")}`,
    `NEXT_PUBLIC_DOWNLOAD_RPM=${get("rpm")}`,
    `NEXT_PUBLIC_DOWNLOAD_APPIMAGE=${get("appimage")}`,
    `NEXT_PUBLIC_DOWNLOAD_DMG=${get("dmg")}`,
    `NEXT_PUBLIC_DOWNLOAD_MSI=${get("msi")}`,
    `NEXT_PUBLIC_DOWNLOAD_EXE=${get("exe")}`,
    `NEXT_PUBLIC_DOWNLOAD_APP_TAR=${get("appTar")}`,
    "",
    `NEXT_PUBLIC_SIZE_DEB=${size("deb")}`,
    `NEXT_PUBLIC_SIZE_RPM=${size("rpm")}`,
    `NEXT_PUBLIC_SIZE_APPIMAGE=${size("appimage")}`,
    `NEXT_PUBLIC_SIZE_DMG=${size("dmg")}`,
    `NEXT_PUBLIC_SIZE_MSI=${size("msi")}`,
    `NEXT_PUBLIC_SIZE_EXE=${size("exe")}`,
    `NEXT_PUBLIC_SIZE_APP_TAR=${size("appTar")}`,
    "",
    `NEXT_PUBLIC_SHA_DEB=${sha("deb")}`,
    `NEXT_PUBLIC_SHA_RPM=${sha("rpm")}`,
    `NEXT_PUBLIC_SHA_APPIMAGE=${sha("appimage")}`,
    `NEXT_PUBLIC_SHA_DMG=${sha("dmg")}`,
    `NEXT_PUBLIC_SHA_MSI=${sha("msi")}`,
    `NEXT_PUBLIC_SHA_EXE=${sha("exe")}`,
    `NEXT_PUBLIC_SHA_APP_TAR=${sha("appTar")}`,
    "",
  ].join("\n");
}

/** Preserve any user-managed keys already in .env.local. */
function preserveUserKeys(existing: string): string {
  // Strip any lines we manage (idempotency: remove our block, then re-add)
  const managedPrefixes = [
    "# Generated by scripts/sync-release.ts",
    "NEXT_PUBLIC_APP_VERSION=",
    "NEXT_PUBLIC_RELEASE_TAG=",
    "NEXT_PUBLIC_RELEASES_URL=",
    "NEXT_PUBLIC_RELEASE_URL=",
    "NEXT_PUBLIC_DOWNLOAD_",
    "NEXT_PUBLIC_SIZE_",
    "NEXT_PUBLIC_SHA_",
  ];
  const lines = existing.split("\n");
  const userLines: string[] = [];
  let inManagedBlock = false;
  for (const line of lines) {
    if (managedPrefixes.some((p) => line === p || line.startsWith(p))) {
      inManagedBlock = true;
      continue;
    }
    if (inManagedBlock && line.trim() === "") {
      inManagedBlock = false;
      continue;
    }
    if (!inManagedBlock) userLines.push(line);
  }
  // Trim trailing blank lines from user block
  while (userLines.length && userLines[userLines.length - 1].trim() === "") {
    userLines.pop();
  }
  return userLines.join("\n");
}

async function main() {
  console.log(`[sync-release] fetching ${API}`);

  // Also load any pre-existing .env.local so we don't lose user keys
  if (existsSync(ENV_FILE)) {
    loadDotenv({ path: ENV_FILE, override: false });
  }

  const result = await fetchLatestRelease();
  if (!result) {
    console.warn("[sync-release] no result — keeping existing .env.local (or skipping)");
    return;
  }

  const existing = existsSync(ENV_FILE) ? readFileSync(ENV_FILE, "utf-8") : "";
  const preserved = preserveUserKeys(existing);
  const managed = buildEnv(result);
  const output = preserved ? `${preserved}\n\n${managed}` : managed;

  writeFileSync(ENV_FILE, output, "utf-8");

  console.log(`[sync-release] wrote ${result.tag} to .env.local`);
  console.log(`[sync-release]   ${result.assets.deb?.size ?? "?"} deb · ${result.assets.dmg?.size ?? "?"} dmg · ${result.assets.msi?.size ?? "?"} msi`);
}

main().catch((err) => {
  console.error("[sync-release] fatal:", err);
  // Don't fail the build on sync errors — fall back to constants.ts
  process.exit(0);
});